[package]
name = "bitter"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]

[dependencies]
byteorder = "1"

[[bench]]
name = "bitget"
harness = false

[[bench]]
name = "bitreader"
harness = false

[dev-dependencies]
criterion = "0.1.2"
bitreader = "0.3.1"
