[package]
name = "bitter"
version = "0.2.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
description = "Swiftly extracts unaligned bit-level data from a byte slice"
repository = "https://github.com/nickbabcock/bitter"
readme = "README.md"
keywords = ["bitstream", "little-endian"]
categories = ["parsing"]
license = "MIT"

[[bench]]
name = "bench_bits"
harness = false

[dev-dependencies]
criterion = "0.2.7"
bitreader = "0.3.1"
bitstream-io = "0.6"
nom = "4"
